type BranchData = {
  slug: string;
  title: {
    en: string;
    pl: string;
    de: string;
  };
  imgUrl?: string;
  address: string;
  team: TeamMember[];
};

type TeamMember = {
  name: string;
  role: string | null;
  email: string;
  phone: string | null;
  img1: string;
  img2: string;
};
const imageBasePath = "/assets/images/contact/team/";
const imageBasePath2 = "/assets/images/gallery/zycie-codzienne/";
const branchData: BranchData[] = [
  {
    slug: "oddzial-buk-mickiewicza",
    title: {
      pl: "Oddział Buk",
      en: "Buk",
      de: "Buk",
    },
    imgUrl: `${imageBasePath2}6.jpg`,
    address: "Mickiewicza, 64-320 Buk",
    team: [
      {
        name: "Agata",
        role: "Office Manager",
        phone: "+48 733 899 885",
        email: "a.gmiat",
        img1: `${imageBasePath}agata-gmiat-1.jpg`,
        img2: `${imageBasePath}agata-gmiat-2.jpg`,
      },
      {
        name: "Jakub",
        role: "CEO",
        phone: null,
        email: "office",
        img1: `${imageBasePath}jakub-1.jpg`,
        img2: `${imageBasePath}jakub-2.jpg`,
      },
      {
        name: "Mikołaj",
        role: "Freight Manager",
        phone: "+48 733 899 884",
        email: "m.wawrzyniak",
        img1: `${imageBasePath}mikolaj-wawrzyniak-1.jpg`,
        img2: `${imageBasePath}mikolaj-wawrzyniak-2.jpg`,
      },
      {
        name: "Kacper",
        role: "Development Manager",
        phone: "+48 733 999 420",
        email: "k.napierala",
        img1: `${imageBasePath}kacper-napierala-1.jpg`,
        img2: `${imageBasePath}kacper-napierala-2.png`,
      },
      {
        name: "Julia",
        role: "Development Manager",
        phone: "+48 733 899 887",
        email: "j.brembor",
        img1: `${imageBasePath}julia-brembor-1.jpg`,
        img2: `${imageBasePath}julia-brembor-2.jpg`,
      },
      {
        name: "Klaudia",
        role: null,
        phone: "+48 733 999 387",
        email: "k.koza",
        img1: `${imageBasePath}klaudia-koza-1.jpg`,
        img2: `${imageBasePath}klaudia-koza-2.jpg`,
      },
      {
        name: "Kamil",
        role: null,
        phone: "+48 733 899 667",
        email: "k.lemanski",
        img1: `${imageBasePath}kamil-lemanski-1.jpg`,
        img2: `${imageBasePath}kamil-lemanski-2.jpg`,
      },
      {
        name: "Monika",
        role: null,
        phone: "+48 733 999 346",
        email: "m.westerska",
        img1: `${imageBasePath}monika-westerska-1.jpg`,
        img2: `${imageBasePath}monika-westerska-2.jpg`,
      },
      {
        name: "Roksana",
        role: null,
        phone: "+48 733 899 033",
        email: "r.sinkiewicz",
        img1: `${imageBasePath}roksana-sinkiewicz-1.jpg`,
        img2: `${imageBasePath}roksana-sinkiewicz-2.jpg`,
      },
      {
        name: "Natalia",
        role: null,
        phone: "+48 733 899 022",
        email: "n.marchewka",
        img1: `${imageBasePath}natalia-marchewka-1.jpg`,
        img2: `${imageBasePath}natalia-marchewka-2.jpg`,
      },
      {
        name: "Mikołaj",
        role: null,
        phone: "+48 733 899 216",
        email: "m.lewandowski",
        img1: `${imageBasePath}mikolaj-lewandowski-1.jpg`,
        img2: `${imageBasePath}mikolaj-lewandowski-2.jpg`,
      },
      {
        name: "Magda",
        role: null,
        phone: "+48 733 899 297",
        email: "m.bialous",
        img1: `${imageBasePath}magda-bialous-1.jpg`,
        img2: `${imageBasePath}magda-bialous-2.jpg`,
      },
      {
        name: "Bartosz",
        role: null,
        phone: "+48 733 899 824",
        email: "b.kujawa",
        img1: `${imageBasePath}bartosz-kujawa-1.jpg`,
        img2: `${imageBasePath}bartosz-kujawa-2.jpg`,
      },
      {
        name: "Julia",
        role: null,
        phone: "+48 733 899 754",
        email: "j.krol",
        img1: `${imageBasePath}julia-krol-1.jpg`,
        img2: `${imageBasePath}julia-krol-2.jpg`,
      },
      {
        name: "Zofia",
        role: null,
        phone: "+48 733 899 751",
        email: "z.miczek",
        img1: `${imageBasePath}zofia-miczek-1.jpg`,
        img2: `${imageBasePath}zofia-miczek-2.jpg`,
      },
      {
        name: "Adam",
        role: null,
        phone: "+48 733 899 429",
        email: "a.hitner",
        img1: `${imageBasePath}adam-hitner-2.jpg`,
        img2: `${imageBasePath}adam-hitner-2.jpg`,
      },
    ],
  },
  {
    slug: "oddzial-buk-wisniowy-sad",
    title: {
      pl: "Oddział Buk",
      en: "Buk",
      de: "Buk",
    },
    imgUrl: `${imageBasePath2}7.jpg`,
    address: "Wiśniowy Sad, 64-320 Buk",
    team: [
      {
        name: "Jakub",
        role: "Freight Manager",
        phone: "+48 733 899 680",
        email: "j.kleszcz",
        img1: `${imageBasePath}jakub-kleszcz-1.jpg`,
        img2: `${imageBasePath}jakub-kleszcz-2.jpg`,
      },
      {
        name: "Mateusz",
        role: null,
        phone: "+48 733 899 774",
        email: "m.nowak",
        img1: `${imageBasePath}mateusz-nowak-1.jpg`,
        img2: `${imageBasePath}mateusz-nowak-2.jpg`,
      },
      {
        name: "Kacper",
        role: null,
        phone: "+48 733 899 659",
        email: "k.bartkowiak",
        img1: `${imageBasePath}kacper-bartkowiak-1.jpg`,
        img2: `${imageBasePath}kacper-bartkowiak-2.jpg`,
      },
      {
        name: "Dawid",
        role: null,
        phone: "+48 733 999 684",
        email: "d.buchert",
        img1: `${imageBasePath}dawid-buchert-1.jpg`,
        img2: `${imageBasePath}dawid-buchert-2.jpg`,
      },
      {
        name: "Filip",
        role: null,
        phone: "+48 733 899 244",
        email: "f.rutkowski",
        img1: `${imageBasePath}filip-rutkowski-1.jpg`,
        img2: `${imageBasePath}filip-rutkowski-2.jpg`,
      },
      {
        name: "Wojtek",
        role: null,
        phone: "+48 733 899 557",
        email: "w.tobys",
        img1: `${imageBasePath}wojtek-tobys-1.jpg`,
        img2: `${imageBasePath}wojtek-tobys-2.jpg`,
      },
      {
        name: "Dawid",
        role: null,
        phone: "+48 729 139 136",
        email: "d.wojtczak",
        img1: `${imageBasePath}dawid-wojtczak-1.jpg`,
        img2: `${imageBasePath}dawid-wojtczak-2.jpg`,
      },
      {
        name: "Marcel",
        role: null,
        phone: "+48 733 899 782",
        email: "m.milosz",
        img1: `${imageBasePath}marcel-milosz-1.jpg`,
        img2: `${imageBasePath}marcel-milosz-2.jpg`,
      },
    ],
  },
  {
    slug: "oddzial-pniewy",
    title: {
      pl: "Oddział Pniewy",
      en: "Pniewy",
      de: "Pniewy",
    },
    imgUrl: `${imageBasePath2}10.jpg`,
    address: "Borówkowa, 62-045 Pniewy",
    team: [
      {
        name: "Kacper",
        role: "Freight Manager",
        phone: "+48 733 899 775",
        email: "k.korpik",
        img1: `${imageBasePath}kacper-korpik-1.jpg`,
        img2: `${imageBasePath}kacper-korpik-2.jpg`,
      },
      {
        name: "Dominik",
        role: null,
        phone: "+48 733 999 203",
        email: "d.gucia",
        img1: `${imageBasePath}dominik-gucia-1.jpg`,
        img2: `${imageBasePath}dominik-gucia-2.jpg`,
      },
      {
        name: "Patryk",
        role: null,
        phone: "+48 733 899 758",
        email: "p.pilarczyk",
        img1: `${imageBasePath}patryk-pilarczyk-1.jpg`,
        img2: `${imageBasePath}patryk-pilarczyk-2.jpg`,
      },
      {
        name: "Vanessa",
        role: null,
        phone: "+48 733 899 107",
        email: "v.wieclawska",
        img1: `${imageBasePath}vanessa-wieclawska-1.jpg`,
        img2: `${imageBasePath}vanessa-wieclawska-2.jpg`,
      },
      {
        name: "Maksymilian",
        role: null,
        phone: "+48 733 899 778",
        email: "m.janik",
        img1: `${imageBasePath}maksymilian-janik-1.jpg`,
        img2: `${imageBasePath}maksymilian-janik-2.jpg`,
      },
      {
        name: "Marcin",
        role: null,
        phone: "+48 733 999 236",
        email: "m.wojciechowski",
        img1: `${imageBasePath}marcin-wojciechowski-1.jpg`,
        img2: `${imageBasePath}marcin-wojciechowski-2.jpg`,
      },
      {
        name: "Jakub",
        role: null,
        phone: "+48 733 799 897",
        email: "j.klapczynski",
        img1: `${imageBasePath}jakub-klapczynski-1.jpg`,
        img2: `${imageBasePath}jakub-klapczynski-2.jpg`,
      },
      {
        name: "Bartosz",
        role: null,
        phone: "+48 733 899 471",
        email: "b.stawinski",
        img1: `${imageBasePath}bartosz-stawinski-1.jpg`,
        img2: `${imageBasePath}bartosz-stawinski-2.jpg`,
      },
      {
        name: "Jakub",
        role: null,
        phone: "+48 733 899 711",
        email: "b.hercog",
        img1: `${imageBasePath}jakub-hercog-1.jpg`,
        img2: `${imageBasePath}jakub-hercog-2.jpg`,
      },
      {
        name: "Julia",
        role: null,
        phone: "+48 733 899 794",
        email: "j.ziolek",
        img1: `${imageBasePath}julia-ziolek-1.jpg`,
        img2: `${imageBasePath}julia-ziolek-2.jpg`,
      },
      {
        name: "Zuzanna",
        role: null,
        phone: "+48 733 899 726",
        email: "z.gluszak",
        img1: `${imageBasePath}zuzanna-gluszak-1.jpg`,
        img2: `${imageBasePath}zuzanna-gluszak-2.jpg`,
      },
      {
        name: "Kacper",
        role: null,
        phone: "+48 733 999 577",
        email: "k.niedzwiedz",
        img1: `${imageBasePath}kacper-niedzwiedz-1.jpg`,
        img2: `${imageBasePath}kacper-niedzwiedz-2.jpg`,
      },
      {
        name: "Marcin",
        role: null,
        phone: "+48 733 899 054",
        email: "m.michalski",
        img1: `${imageBasePath}marcin-michalski-1.jpg`,
        img2: `${imageBasePath}marcin-michalski-2.jpg`,
      },
      {
        name: "Kamil",
        role: null,
        phone: "+48 733 899 726",
        email: "k.giza",
        img1: `${imageBasePath}kamil-giza-1.jpg`,
        img2: `${imageBasePath}kamil-giza-2.jpg`,
      },
      {
        name: "Paweł",
        role: null,
        phone: "+48 733 999 856",
        email: "p.gurzynski",
        img1: `${imageBasePath}pawel-gurzynski-1.jpg`,
        img2: `${imageBasePath}pawel-gurzynski-2.jpg`,
      },
      {
        name: "Hubert",
        role: null,
        phone: "+48 733 899 658",
        email: "h.jankowiak",
        img1: `${imageBasePath}hubert-jankowiak-1.jpg`,
        img2: `${imageBasePath}hubert-jankowiak-2.jpg`,
      },
      {
        name: "Mikołaj",
        role: null,
        phone: "+48 733 899 286",
        email: "m.nowak",
        img1: `${imageBasePath}mikolaj-nowak-1.jpg`,
        img2: `${imageBasePath}mikolaj-nowak-2.jpg`,
      },
    ],
  },
  {
    slug: "oddzial-opalenica",
    title: {
      pl: "Oddział Opalenica",
      en: "Opalenica",
      de: "Opalenica",
    },
    imgUrl: `${imageBasePath2}9.jpg`,
    address: "Zamkowa, 64-330 Opalenica",
    team: [
      {
        name: "Patryk",
        role: "Freight Manager",
        phone: "+48 733 899 752",
        email: "p.giel",
        img1: `${imageBasePath}patryk-giel-1.jpg`,
        img2: `${imageBasePath}patryk-giel-2.jpg`,
      },
      {
        name: "Roksana",
        role: null,
        phone: "+48 733 899 545",
        email: "r.lotka",
        img1: `${imageBasePath}roksana-lotka-1.jpg`,
        img2: `${imageBasePath}roksana-lotka-2.jpg`,
      },
    ],
  },
  {
    slug: "oddzial-glinno",
    title: {
      pl: "Oddział Glinno",
      en: "Glinno",
      de: "Glinno",
    },
    imgUrl: `${imageBasePath}glinno.jpg`,
    address: "Grudniowa, 64-300 Glinno",
    team: [
      {
        name: "Filip",
        role: null,
        phone: "+48 733 999 435",
        email: "f.strzyzynski",
        img1: `${imageBasePath}filip-strzyzynski-1.jpg`,
        img2: `${imageBasePath}filip-strzyzynski-2.jpg`,
      },
      {
        name: "Maja",
        role: null,
        phone: "+48 733 899 058",
        email: "m.szkuta",
        img1: `${imageBasePath}maja-szkuta-1.jpg`,
        img2: `${imageBasePath}maja-szkuta-2.jpg`,
      },
      {
        name: "Aleksander",
        role: null,
        phone: "+48 733 899 862",
        email: "a.kiezel",
        img1: `${imageBasePath}aleksander-kiezel-1.jpg`,
        img2: `${imageBasePath}aleksander-kiezel-2.jpg`,
      },
    ],
  },
  {
    slug: "oddzial-tarnowo-podgorne",
    title: {
      pl: "Oddział Tarnowo Podgórne",
      en: "Tarnowo Podgórne",
      de: "Tarnowo Podgórne",
    },
    imgUrl: `${imageBasePath2}8.jpg`,
    address: "Florencka, 62-080 Tarnowo Podgórne",
    team: [
      {
        name: "Filip",
        role: "Development Manager",
        phone: "+48 733 899 882",
        email: "f.marcinkowski",
        img1: `${imageBasePath}filip-marcinkowski-1.jpg`,
        img2: `${imageBasePath}filip-marcinkowski-2.jpg`,
      },
      {
        name: "Klaudiusz",
        role: null,
        phone: "+48 733 999 057",
        email: "k.lesny",
        img1: `${imageBasePath}klaudiusz-lesny-1.jpg`,
        img2: `${imageBasePath}klaudiusz-lesny-2.jpg`,
      },
      {
        name: "Patryk",
        role: null,
        phone: "+48 733 999 483",
        email: "p.sobarnia",
        img1: `${imageBasePath}patryk-sobarnia-1.jpg`,
        img2: `${imageBasePath}patryk-sobarnia-2.jpg`,
      },
      {
        name: "Sandra",
        role: null,
        phone: "+48 733 899 419",
        email: "s.rutkowska",
        img1: `${imageBasePath}sandra-rutkowska-1.jpg`,
        img2: `${imageBasePath}sandra-rutkowska-2.jpg`,
      },
    ],
  },
];

export { branchData };
export type { BranchData, TeamMember };
